//
//  Constants.swift
//  FurryAdventure
//
//  Created by Sang Saephan on 3/28/17.
//  Copyright © 2017 Sticky Gerbils. All rights reserved.
//

import Foundation

let vegetables = ["garlic", "onion", "olive", "tomato", "potato", "salad greens", "carrot", "basil", "parsley", "rosemary", "bell pepper", "chili pepper", "corn", "ginger", "mushroom", "broccoli", "spinach", "green beans", "celery", "red onion", "cilantro", "cucumber", "pickle", "dill", "avocado", "sweet potato", "zucchini", "shallot", "mixed vegetable", "cabbage", "asparagus", "cauliflower", "mint", "pumpkin", "kale", "frozen vegetables", "scallion", "squash", "sun dried tomato", "horseradish", "sweet corn", "beet"]

let fruits = ["lemon", "banana", "apple", "coconut", "mango", "lime", "orange", "pineapple", "strawberries", "raisin", "blueberries", "grapefruit", "grape", "prunes", "nectarine", "fig", "peach", "cranberries", "raspberries", "pear", "cherry", "apricot", "blackberries", "berries", "date", "watermelon", "kiwi", "craisins", "mandarin", "cantaloupe", "plum", "papaya", "pomegranate", "apple butter", "clementine", "rhubarb", "tangerine", "sultanas", "currant", "plantain", "passion fruit", "persimmons", "quince", "lychee", "tangelos", "lingonberry", "kumquat", "boysenberry", "star fruit", "guava"]

let meat = ["chicken breast", "ground beef", "bacon", "sausage", "cooked chicken", "ham", "veal", "beef steak", "hot dog", "pork chops", "chicken thighs", "ground turkey", "pork", "turkey", "pepperoni", "whole chicken", "chicken leg", "ground pork", "chicken wings", "chorizo", "polish sausage", "salami", "pork roast","ground chicken", "pork ribs", "venison", "spam", "lamb", "pork shoulder", "beef roast", "bratwurst", "prosciutto", "chicken roast", "bologna", "corned beef", "lamb chops", "ground lamb", "beef ribs", "duck", "pancetta", "beef liver", "leg of lamb", "chicken giblets", "beef shank", "pork belly", "cornish hen", "lamb shoulder", "lamb shank"]

let dairy = ["butter", "eggs", "milk", "parmesan", "cheddar", "cream", "sour cream", "cream cheese", "mozzarella", "american cheese", "yogurt", "evaporated milk", "condensed milk", "whipped cream", "half and half", "monterey jack cheese", "feta", "cottage cheese", "ice cream", "goat cheese", "frosting", "swiss cheese", "buttermilk", "velveeta", "ricotta", "powdered milk", "blue cheese", "provolone", "colby cheese", "gouda", "pepper jack", "italian cheese", "soft cheese", "romano", "brie", "pepperjack cheese", "custard", "cheese soup", "pizza cheese", "ghee", "pecorino cheese", "gruyere", "creme fraiche", "neufchatel", "muenster", "asiago", "queso fresco cheese", "hard cheese", "havarti cheese", "mascarpone"]

let grainsAndCarbs = ["wheat germ", "flour", "rice", "pasta", "bread", "baking powder", "bread flour", "baking soda", "bread crumbs", "cornstarch", "semolina", "noodle", "rolled oats", "yeast", "cracker", "quinoa", "pancake mix", "flour tortillas", "cornmeal", "chips", "saltines", "brown rice", "popcorn", "self rising flour", "macaroni cheese mix", "corn tortillas", "stuffing mix", "biscuits", "couscous", "pie crust", "pita", "bisquick", "cereal", "angel hair", "croutons", "lasagne", "ramen", "baguette", "pizza dough", "barley", "puff pastry", "cake mix", "bagel", "pretzel", "cream of wheat", "multigrain bread", "crescent roll dough", "pierogi", "hot dog bun", "filo dough", "wheat", "ravioli", "muffin mix", "gnocchi", "bread dough", "potato flakes", "rye", "croissants", "matzo meal", "shortcrust pastry", "ciabatta", "breadsticks", "angel food", "risotto", "spelt"]

let herbsAndSpices = ["red pepper flake", "cinnamon", "chive", "vanilla", "garlic powder", "oregano", "paprika", "cayenne", "chili powder", "cumin", "italian seasoning", "thyme", "peppercorn", "nutmeg", "onion powder", "curry powder", "clove", "bay leaf", "taco seasoning", "sage", "ground nutmeg", "chinese five spice", "allspice", "turmeric", "ground coriander", "coriander", "cajun seasoning", "steak seasoning", "herbs", "celery salt", "vanilla essence", "poultry seasoning", "marjoram", "tarragon", "cardamom", "celery seed", "garam masala", "mustard seed", "chile powder", "italian herbs", "saffron", "caraway", "herbes de provence", "italian spice", "star anise", "savory", "dill seed", "aniseed", "cacao", "tamarind"]
